/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
}

// gradlew ParkingGarageSimulation --args="arg1 arg2 arg3"
tasks.register<JavaExec>("ParkingGarageSimulation"){
    mainClass = "ParkingGarageSimulation.Main"
    classpath = sourceSets["main"].runtimeClasspath
    standardInput = System.`in`
}
